### ISSUE TITLE
能把最大音量搞大点吗，黑苹果声音只有win10 一半

### ISSUE THREAD

**Issue by Ahian** [Endermanpoi/XPS9550-Mojave#1]

**Comment by Endermanpoi** [comment]
你不提我还没有发现，不过对我来说没有影响。
修改DSDT我不太会，或许你可以去大佬那里提问看看，虽然大佬好久没有出现了。
我倒是找了一个软件来实现提高音量[Sound Booster](https://froyosoft.com/soundbooster.php)，实验了一下免费的Lite版可以用，至于达不达到你要的效果我就不知道了。

**Comment by Ahian** [comment]
非常感谢您的回复，我立刻试试
