### ISSUE TITLE
请问1080P的屏幕要修改什么参数？

### ISSUE THREAD

**Issue by pyj760010** [Endermanpoi/XPS9550-Mojave#2]
屏幕:4K（1080P config.plist中启动背景->UI比例改为1）请问根据这句话，我修改那一条参数，不太懂，求教了！多谢！

**Comment by Endermanpoi** [comment]
啊，我说的是指用clover configurator图形化设置config.plist时，启动背景 分类下的 UI比例 的值。纯文本的话，是这里
```
<key>BootGraphics</key>
<dict>
    <key>UIScale</key>
    <integer>2</integer>
</dict>
```

**Comment by Endermanpoi** [comment]
或者直接把这个参数`UIScale`这两行删了，Clover默认就是1

**Comment by pyj760010** [comment]
嗯嗯，好呢，谢谢啦！
