### ISSUE TITLE
请问i5版本需要修改哪里

### ISSUE THREAD

**Issue by Ahian** [Endermanpoi/XPS9550-Mojave#3]

**Comment by Endermanpoi** [comment]
毕竟只有一台，我不是很清楚，引用[大佬的教程](https://github.com/wmchris/DellXPS15-9550-OSX/blob/10.14/Tutorial_10.14.md)

>If your PC has a Core i5 processor, you'll have to modify your config.plist in EFI/CLOVER/: search for the Key ig-platform-id: 0x191b0000 and replace it with 0x19160000. Also search for AAPL,ig-platform-id: AAAbGQ== and change it to AAAWGQ== 

但是在我的config.plist并没有找到前一个修改的地方，你研究一下试试看吧

**Comment by Endermanpoi** [comment]
研究了一下更新了readme，你看一下吧
