### ISSUE TITLE
升级后15.4后唤醒，问题。

### ISSUE THREAD

**Issue by Beipy** [Endermanpoi/XPS9550-Mojave#5]
无法唤醒外接HDMI显示器，

**Comment by Endermanpoi** [comment]
emmmmm，或许是EDID的问题，但是我试了Hackintool注入EDID也没有成功，等看看其他大佬怎么解决吧

**Comment by Endermanpoi** [comment]
> 无法唤醒外接HDMI显示器，

WhateverGreen更新到1.3.8+，启动参数里加上 `igfxonln=1`
