### ISSUE TITLE
睡眠唤不醒

### ISSUE THREAD

**Issue by kay1ess** [Endermanpoi/XPS9550-Mojave#6]
请问又遇到睡眠唤不醒的情况吗 我的只要睡眠了 就唤不醒

**Comment by jockey1230** [comment]
苹果的休眠文件是加密的clover读取不了所以会造成无法唤醒的情况，把睡眠模式改成0禁用休眠文件就可以了

sudo pmset -a hibernatemode 0
sudo pmset -a autopoweroff 0
sudo pmset -a standby 0
sudo pmset -a proximitywake 0

**Comment by kay1ess** [comment]
> 苹果的休眠文件是加密的clover读取不了所以会造成无法唤醒的情况，把睡眠模式改成0禁用休眠文件就可以了
> 
> sudo pmset -a hibernatemode 0
> sudo pmset -a autopoweroff 0
> sudo pmset -a standby 0
> sudo pmset -a proximitywake 0
 
这样屏幕会影响熄屏吗

**Comment by kay1ess** [comment]
还有个问题 亮度控制键失灵了  之前在windows上也不知道什么时候开始 亮度键按了没有反应

**Comment by Endermanpoi** [comment]
> 还有个问题 亮度控制键失灵了 之前在windows上也不知道什么时候开始 亮度键按了没有反应

你说的休眠倒是[黑手之前的教程](https://github.com/darkhandz/XPS15-9550-High-Sierra#%E7%A6%81%E6%AD%A2%E7%94%9F%E6%88%90%E4%BC%91%E7%9C%A0%E6%96%87%E4%BB%B6)里有提到过，不过我的没有这情况就没有设置；亮度的话，既然win下也一样，可能是你电脑本身的锅了，爱莫能助
